[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/apihome/*"
  to = " https://homeaccesscenterapi.vercel.app/:splat"
  status = 200
[[redirects]]
  from = "/api/*"
  to = " https://homeaccesscenterapi.vercel.app/api/:splat"
  status = 200
  
